### ISSUE TITLE
document software installation

### ISSUE THREAD

**Issue by mushon** [mushon/IWBA#13]

**Comment by wonyoungso** [comment]
Since we're done with initial setting, maybe it will be helpful to document just updating the code to heroku.
1. (important) recompile javascript
   `rm -rf public/webpack`
   `bundle exec rake webpack:compile`
2. push all code into github repository
   `git pull`
   `git add .`
   `git commit -m 'update'`
   `git push`
3. heroku login (skip if you already logged in)

`heroku login`
And type your heroku email and password
1. `git push heroku master`
